name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: 1 6 * * 2
  workflow_dispatch:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: 'Build:dockerimage'
        if: success()
        uses: docker/build-push-action@v2
        with:
          registry: ghcr.io
          username: "rguichard"
          password: ${{ secrets.PAT }}
          repository: mpepping/jenkins
          tags: latest

# 401 Unable to push README.md to Docker Hub
#      - name: Update Docker hub metadata
#        uses: docker://mpepping/docker-hub-metadata-github-action
#        env:
#          IMAGE: mpepping/jenkins
#          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
