name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: 1 6 * * 2
  workflow_dispatch:

jobs:
  build:
    name: 'Build Jenkins image'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: Log in
        run: |
          echo $PAT | docker login ghcr.io --username mpepping --password-stdin
        env:
          PAT: ${{ secrets.COMMITTER_TOKEN }}
      - name: Build image
        run: |
          docker build --tag ghcr.io/mpepping/jenkins:latest
        env:
          VERSION: ${{ github.event.inputs.version }}
      - name: Deploy image
        run: |
          docker push ghcr.io/mpepping/jenkins:latest
        env:
          VERSION: ${{ github.event.inputs.version }}
            GIT_AUTH_TOKEN=${{ github.token }}
